name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/alucard.jpg
    - assets/cancun-1228131_640.jpg
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf